<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="PRG_IM1L1_PPM" Id="{280e2bcd-0287-45b1-b768-ade5bf5e5119}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_IM1L1_PPM
VAR
	fbMotion1: FB_SimMotor;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Placeholder, standard simulated motion for all axes
fbMotion1(stMotionStage := Main.M23);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>