<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PRG_1_PlcTask" Id="{d56e695c-51d1-4f46-b1a7-5260b516ea58}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_1_PlcTask
(*
    Launch site for each component's program
    Only "fast" programs are allowed here,
    anything else needs to be relegated to a second task
*)]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_2_PMPS_PRE();

PRG_AT2L0_SOLID();
PRG_IM1L0_XTES();
PRG_IM1L1_PPM();
PRG_IM2L0_XTES();
PRG_IM3L0_PPM();
PRG_IM4L0_XTES();
PRG_PF1L0_WFS();
PRG_RTDSL0();
PRG_RTDSX0_Three_Stage();
PRG_SL1L0_POWER();
PRG_SL2L0_POWER();
PRG_SP1L0_KMONO();

PRG_3_PMPS_POST();
PRG_4_LOG();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>