<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="PRG_4_LOG" Id="{481906ac-7b04-0833-0c94-35bab68178b7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_4_LOG
VAR
    fbLogHandler: FB_LogHandler;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbLogHandler();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>