IOC_TOP = /reg/g/pcds/epics/ioc/common/ads-ioc/R0.2.1
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = plc-lfe-motion
PROJECT_PATH := ../../plc-lfe-motion/plc-lfe-motion.tsproj
PLC = lfe_motion

PREFIX = PLC:LFE:MOTION

include $(IOC_TOP)/iocBoot/templates/Makefile.base
