IOC_TOP = /reg/neh/home/zlentz/github/ads-ioc
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = plc-lfe-motion
PROJECT_PATH := ../../plc-lfe-motion/plc-lfe-motion.tsproj
PLC = lfe_motion

PYTMC_OPTS = --only-motor
PREFIX = TST:MOTION

include $(IOC_TOP)/iocBoot/templates/Makefile.base
