<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="FB_HardwareFFOutput" Id="{8c2f0148-9967-4c03-964c-9a83e44c0f77}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HardwareFFOutput
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_HardwareFFOutput">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>